"""empty message

Revision ID: 074d647f0e18
Revises: 
Create Date: 2020-03-06 22:05:42.927264

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '074d647f0e18'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'actors', ['id'])
    op.create_unique_constraint(None, 'movies', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'movies', type_='unique')
    op.drop_constraint(None, 'actors', type_='unique')
    # ### end Alembic commands ###
