"""empty message

Revision ID: 813647e65eee
Revises:
Create Date: 2020-02-16 17:23:48.441445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '813647e65eee'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actors',
                    sa.Column('id', sa.Integer(),
                              autoincrement=True, nullable=False),
                    sa.Column('name', sa.String(length=80), nullable=True),
                    sa.Column('age', sa.String(length=180), nullable=False),
                    sa.Column('gender', sa.String(length=80), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('name')
                    )
    op.create_table('movies',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('title', sa.String(length=80), nullable=True),
                    sa.Column('release_date', sa.String(
                        length=180), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('title')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movies')
    op.drop_table('actors')
    # ### end Alembic commands ###
